### ISSUE TITLE
Version 2.1 of Here API being retired

### ISSUE THREAD

**Issue by bdk0172** [wandersoncs/leaflet-tilelayer-here#1]
We recently received notification from Here that they are retiring some versions of their API.  We are using your package to display Here map tiles and your code references 2.1 which is one of the versions being retired.  Are you planning on updating this in the near future?  Or will we have to manually make changes to the JavaScript file?  They suggest migrating to the newer versions by Sept. 30th and will stop maintaining 2.1 on Dec. 31st.

IMPORTANT
We have analyzed your API consumption and have identified that you are currently using the following product being retired.

Batch Geocoder API 6.2
Forward Geocoder API 6.2
Map Tile API 2.1 - Aerial\Satellite Proxy
Map Tile API 2.1 - Base
Reverse Geocoder API 6.2

**Comment by wandersoncs** [comment]
Hello!
Thanks for open this issue and letting me know about the version will be deprecated.

I'll be working in the update this week.

**Comment by bdk0172** [comment]
It appears you can no longer use app_id and app_code anymore either.

All our customers today can benefit from these new features and capabilities when accessing the newest versions of the HERE Location Services. If you are already using token or API key authentication, then no change regarding access credentials is needed.  

If, however, you’re still using app_id and app_code, please check out the documentation posted at https://developer.here.com/documentation/authentication where you will find information on how to create and use new credentials.

**Comment by bdk0172** [comment]
I was able to find the migration guide from v2 to v3 of the tile API.

https://developer.here.com/documentation/raster-tile-api/migration_guide/index.html

**Comment by wandersoncs** [comment]
Hello @bdk0172, I created a pull request with the necessary changes, if you want to review the code, link is below:

[Migrate HERE Map Tile API v2 to HERE Raster Tile API v3](https://github.com/wandersoncs/leaflet-tilelayer-here/pull/2).

**Comment by wandersoncs** [comment]
To use HERE Raster Tile API, update the library dependence to 2.0.0.

**Comment by bdk0172** [comment]
Thanks for getting this updated so quickly.
